const centerData = [
  {
    type: 'input',
    id: 'xm2020',
    name: '姓名',
    title: '',
    titlePlaceholder: '姓名',
    defaultVal: '',
    placeholder: '',
    isMustFill: false,
    minVal: 0,
    maxVal: 0,
    widthPos: '0.5',
    isHide: 0
  },
  {
    type: 'radio',
    id: 'xb2020',
    name: '性别',
    title: '',
    titlePlaceholder: '您的性别',
    defaultVal: '',
    // defaultArr: [{lableV: 1, val: '男'}, {lableV: 2, val: '女'}, {lableV: 3, val: '不想透露'}],
    isMustFill: false,
    widthPos: '1.0',
    isHide: 0,
    direction: 0
  },
  {
    type: 'TimePicker',
    id: 'time2020',
    name: '时间选择器',
    title: '',
    titlePlaceholder: '时间选择器',
    defaultVal: '',
    placeholder: '',
    isMustFill: false,
    widthPos: '0.5',
    isHide: 0
  },
  {
    type: 'DatePicker',
    id: 'date2020',
    name: '日期选择器',
    title: '',
    titlePlaceholder: '日期选择器',
    defaultVal: '',
    placeholder: '',
    isMustFill: false,
    widthPos: '0.5',
    isHide: 0
  },
  {
    type: 'DateTimePicker',
    id: 'timedate2020',
    name: '日期时间选择器',
    title: '',
    titlePlaceholder: '日期时间选择器',
    defaultVal: '',
    placeholder: '',
    isMustFill: false,
    widthPos: '0.5',
    isHide: 0
  },
  {
    type: 'input',
    id: 'dhwz2020',
    name: '单行文字',
    title: '',
    titlePlaceholder: '单行文字',
    defaultVal: '',
    placeholder: '',
    isMustFill: false,
    minVal: 0,
    maxVal: 0,
    widthPos: '0.5',
    isHide: 0
  },
  {
    type: 'textarea',
    id: 'dhwzs2020',
    name: '多行文字',
    title: '',
    titlePlaceholder: '多行文字',
    defaultVal: '',
    placeholder: '',
    isMustFill: false,
    minVal: 0,
    maxVal: 0,
    widthPos: '1.0',
    isHide: 0
  },
  {
    type: 'radio',
    id: 'dxxz2020',
    name: '单项选择',
    title: '',
    titlePlaceholder: '未命名',
    defaultVal: 1,
    // defaultArr: [{lableV: 1, val: '选择'}, {lableV: 2, val: '选择'}],
    isMustFill: false,
    widthPos: '1.0',
    isHide: 0,
    direction: 0
  },
  {
    type: 'checkbox',
    id: 'dxxzs2020',
    name: '多项选择',
    title: '',
    titlePlaceholder: '未命名',
    defaultVal: [],
    // defaultArr: ['选择1', '选择2', '选择3'],
    isMustFill: false,
    widthPos: '1.0',
    isHide: 0,
    direction: 0
  },
  {
    type: 'edit',
    id: 'wbbj2020',
    name: '文本编辑',
    title: '',
    titlePlaceholder: '文本编辑',
    defaultVal: '',
    isMustFill: false,
    widthPos: '1.0',
    isHide: 0
  }
]
export default centerData
